version: '3.8'
services:
  db:
    container_name: postgres_db_container
    image: postgres:12
    restart: always
    networks:
      - db_network
      - api_network
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: Tema2
      POSTGRES_USER: Tema2_user
      POSTGRES_PASSWORD: 1234
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./initialization_scripts/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

  sgbd:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    networks:
      - db_network
    ports:
      - "8081:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: tema2@tema2.com
      PGADMIN_DEFAULT_PASSWORD: 1234
      PGADMIN_LISTEN_PORT: 80
    depends_on:
      - db
    volumes:
      - sgbd_data:/var/lib/pgadmin
      - ./initialization_scripts/servers.json:/pgadmin4/servers.json

  api:
    container_name: rest_server
    build: .
    image: tema2_server
    restart: always
    networks:
      - api_network
    ports:
      - "8080:5000"
    depends_on:
      - db

volumes:
  db_data: {}
  sgbd_data: {}

networks:
  db_network:
  api_network:
