CREATE TABLE IF NOT EXISTS Tari(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nume_tara VARCHAR ( 50 ) UNIQUE,
    latitudine DOUBLE PRECISION,
    longitudine DOUBLE PRECISION
);

CREATE TABLE IF NOT EXISTS Orase(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_tara INT REFERENCES Tari(id) ON UPDATE CASCADE ON DELETE CASCADE,
    nume_oras VARCHAR (50 ),
    latitudine DOUBLE PRECISION,
    longitudine DOUBLE PRECISION,
    CONSTRAINT "unique_tara_oras" UNIQUE (id_tara, nume_oras)
);

CREATE TABLE IF NOT EXISTS Temperaturi(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    valoare DOUBLE PRECISION,
    "timestamp" TIMESTAMP,
    id_oras INT REFERENCES Orase(id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT "unique_oras_timestamp" UNIQUE (id_oras,timestamp)
);